---
title: "Model Overview"
author: "Severin Reissl and Luis Sarmiento"
format: 
  html: 
    toc: true
    warning: false
    code-fold: true
    code-summary: "Show the Code"
    fontsize: "14px"
---

# Background

Before providing a detailed outline of the model (see below), we briefly describe the basic intuition underlying the agent-based model we use to simulate the household decision to adopt a technology. At present, the model only depicts the adoption of photovoltaic (PV) systems, but a similar framework could also be applied to other technologies such as heat pumps, insulation, or AC systems.

The adoption decision in the model is based on a simple expected utility framework; in every period $t = 1,...,T$ (where one period represents one year), each household $h = 1,...,N$ who does not already own PV faces the binary decision whether or not to purchase the single type of PV system available in the model. The expected utility from owning PV is a function of the (discounted) profit $h$ expects to derive from the ownership of PV over the lifetime of the panel, as well as a component based on social influence/emulation and one based on the environmental attitude of $h$. The expected profit from owning PV (stemming from an expected reduction in outlays for electricity and earnings through electricity fed into the grid) is in turn a function of the future electricity price expected by $h$ as well as the feed-in tariff and the future electricity consumption of $h$.

Households receive income, consume and pay electricity cost, resulting in changes in their stocks of liquid assets; these liquid assets can be used to purchase a solar panel. Households with insufficient liquid assets may also request a loan to install PV from a stylised banking sector, but may be credit-rationed if the bank is unwilling to lend them as much as they require.

# Model description

The **sequence of events** taking place in every simulation period only consists of a few steps:

::: incremental
-   Set current electricity price
-   Determine income and electricity cost for each household; calculate revenue/cost saving for PV owners
-   Update income distribution statistics
-   Based on new income distribution determine consumption expenditure. Calculate saving, apply debt service for each household with positive debt and update liquidity
-   Augment the age of existing solar panels; scrap those which exceed the maximum lifespan
-   Update households' expectations of future electricity price
-   Adoption decision; update state variables of agents who adopt PV
:::

## Electricity price

Depending on the year which a given simulation period $t$ is supposed to represent (past or future), the current electricity price to be paid by households in period $t$[^1] is either taken from a time-series of household-level electricity prices for Germany obtained from Eurostat, or simulated using an AR(1) model previously estimated on this empirical time-series.
To estimate this AR(1) model, the time-series was differenced and then used to estimate the intercept ($\phi_1$) and autoregressive ($\phi_2$) parameter, with the residuals used to calculate the standard deviation of random shocks ($\sigma^p$).

If no empirical observation is available for the electricity price in $t$ (because $t$ represents some year in the future), the electricity price in the model in $t$ is given by:

[^1]: Note that this is distinct from the price which any household may expect to prevail in the future; described below.

$$
    p_t=p_{t-1}+\phi_1+\phi_2 \Delta p_{t-1}+\epsilon^p_t \rightarrow \epsilon^p_t\sim\mathcal{N}(0,\sigma^p)
$$

## Income and electricity costs

In every simulation period, we simulate the income of household $h=1,...,N$ using a draw from the normally distributed variable $Y^h_t$ with mean $\overline{Y^h_t}$ and standard deviation $\widehat{Y^h_t}$.

$$
    Y^h_t\sim \mathcal{N}\left(\overline{Y^h_t},\widehat{Y^h_t}\right)
$$

The mean, $\overline{Y^h_t}$, is initialised using the income of $h$ according to the SOEP data and grows at rate $g^h$ in every period thereafter, i.e. $\overline{Y^h_t}=(1+g^h)\overline{Y^h_{t-1}}$. $\widehat{Y^h_t}$ is given by $\overline{Y^h_t}\cdot\sigma^y_d$ where $\sigma^y_d$ is the standard deviation of income within the income decile $d$ of household $h$ in the SOEP data (expressed as % of average income in that decile)

The electricity consumption of each household (in kWh) is instead a deterministic variable, denoted $\overline{E^h_t}$. As with income, $\overline{E^h_t}$ is initialised using the electricity consumption of $h$ taken from SOEP data (deflated by the empirical electricity price for the start year from the Eurostat dataset) and grows at rate $g^h$ in every period thereafter, i.e. $\overline{E^h_t}=(1+g^h)\overline{E^h_{t-1}}$.

The cost of electricity to be paid by $h$ would then be $CE^h_t=p_t \overline{E^h_t}$. If $h$ owns a solar panel ($PV^h_t=1$), however, this electricity cost will be reduced by the cost saving/revenue generated by the panel. The overall cost saving/revenue derived from a solar panel depends on two factors:

::: incremental
-   Whether the current electricity consumption of $h$, $\overline{E^h_t}$, is larger or smaller than the amount of electricity $G$ which a solar panel can produce per period.
-   Whether the feed-in tariff, $FIT^h_t$ that $h$ receives by selling the electricity that their panel produces is larger or smaller than the current price of electricity, $p_t$.
:::

Since we assume that there is only one model of solar panel which agents can purchase and since we abstract from any variations in electricity output across agents due e.g. to hours of sun, position of the panel, etc., $G$ is fixed, exogenous, and identical for all agents who own PV. 
$FIT^h_t$ varies across agents; in particular, as is the case in reality in Germany, $FIT^h_t$ depends on the year in which the solar panel was installed. For instance, if $h$ bought a solar panel in 2015, they will receive the 2015 feed-in tariff (taken from empirical data for Germany) for the next 20 years (regardless of what happens to the electricity price), as is the case in reality. For simplicity, we assume that the lifespan of a panel is also 20 years (which is a broadly realistic value based on information material available online). The second condition above is important particularly because in the 2000s, the feed-in tariff in Germany for small PV units (up to 10kWp) was in fact *higher* than the average electricity price. When simulating past years, actual feed-in tariffs in force in the respective years are used. When simulating future years, the feed-in tariff is kept constant at its most recent value in the baseline simulation. 

If $FIT^h_t>p_t$, it is rational for the household to sell all electricity generated by the panel to the grid and buy any electricity needed back at the lower price; its electricity cost hence becomes

$$
    CE^h_t=p_t \overline{E^h_t}-FIT^h_tG
$$
Note that this quantity may also be negative.

If $FIT^h_t<p_t$, the household would want to consume some or even all of the electricity generated by the panel. Since we are assuming that PV systems in the model are not equipped with batteries, however, agents can only consume a maximum of $\eta G$ of the electricity generated by the panel, where $\eta$ is calibrated to the average share of own consumption out of electricity generated by household PV systems without a battery (information on this value was taken from consumer advice websites). Consequently, the electricity costs for households who own PV and for whom $FIT^h_t<p_t$ is given by


$$
  CE^h_t=p_t \overline{E^h_t}-G\eta p_t-G(1-\eta)FIT^h_t
$$
for households for whom $\overline{E^h_t}\geq G$ and by

$$
CE^h_t=p_t \overline{E^h_t}-min\left(\eta G,\overline{E^h_t}\right)p_t-FIT^h_t\left(G-min\left(\eta G,\overline{E^h_t}\right)\right)
$$
for households for whom $\overline{E^h_t}< G$.

Households who own PV keep track of the cumulative profit they have derived from their panel. In order to do so, the variable $\Pi^h$ is updated in every period by adding the respective current saving on electricity cost/revenue from selling to the grid.

In addition to ``gross" income defined above, we also keep track of income net of electricity cost:

$$
    Y^{p,h}_t=min\left(0,Y^h_t-CE^h_t\right)
$$

We then calculate income distribution statistics (percentiles and deciles, used below) for period $t$ using this income net of electricity cost.

## Consumption

Each household devotes a part of its ``gross" income to consumption expenditures (excluding electricity consumption which is determined as described above). The average propensity to consume of $h$, $c^h_t$, is determined using survey data from the German Federal Statistical Office, which gives household consumption expenditure by income group, converted into percentiles using SOEP data. $c^h_t$ is hence the average propensity to consume of the income percentile in which $h$ finds itself in period $t$. The desired consumption expenditure of $h$ is then given by

$$
    C^h_t=(1-\mu)C^h_{t-1}+\mu c^h_t Y^{p,h}_t
$$

where $\mu$ is a parameter giving the speed at which consumption expenditure adjusts to changes in income. In the initial period, we set $C^h_t=c^h_t Y^{p,h}_t$.

\subsection*{Saving, debt service and liquidity updating}

Each household in the model holds a stock of liquid assets (money) which is augmented by income and can be used to consume, pay for electricity, service debt and purchase a solar panel. To update the liquidity of $h$, we first calculate the difference between income on the one hand and desired consumption expenditure and electricity cost on the other:

$$
    Save^h_t=Y^h_t-C^h_t-CE^h_t
$$

Recall that if $PV^h_t=1$, $CE^h_t$ may be negative.

In the first instance, $Save^h_t$ is added to existing liquidity. Note that we assume that households cannot hold negative liquidity; if saving is negative and larger than previously accumulated liquidity, liquidity is set to 0 (implicitly assuming that the household reduces desired consumption expenditure and/or expenditure on electricity in order to be able to afford the payments):

$$
    M^h_t=max\left(0,M^h_{t-1}+Save^h_t\right)
$$

In the model, households may incur debt in order to purchase a solar panel. At the beginning of the simulation, the debt of all households (including those already owning PV) is initialised to 0. In any period $t>0$, households which in the past used a loan in order to buy PV and have not yet fully paid it off must make a debt service payment consisting of interest and principal payments, denoted by $S^h$. $S^h$ is determined when a household takes out a loan in order to adopt PV. Its calculation is explained in the description of the adoption decision below.

Payments for debt service are made out of the stock of liquidity updated above:

$$
    M^h_t=max\left(0,M^h_t-S^h_t\right)
$$

Note that here, too, we assume that payments cannot lead to negative liquidity! If a household is unable to (fully) make its debt service payment out of liquidity, it pays as much as it can, making first the interest payment and then the principal payment. Unpaid principal payments mean that the stock of debt does not decrease as much as it would if the payment were made in full. Any unpaid *interest* payments are *added* to the household's outstanding debt. In both of these cases, $S^h$, i.e. the per-period debt service to be paid in the future is re-calculated taking into account unpaid principal and/or interest payments and the remaining term of the loan. In addition, any interest paid is subtracted from the cumulative profit derived from owning PV, $\Pi^h$ as it represents a cost.

In a final step, we include a saving allocation choice. This is done to make sure that average household liquidity does not grow too fast. In particular we assume that

$$
    M^h_t=M^h_{t-1}+\theta^h_t(M^h_t-M^h_{t-1}) \quad if\ M^h_t>M^h_{t-1}
$$

i.e. we assume that if the household has positive saving, it puts only part of this into liquid assets (bank deposits etc.). $\theta^h_t$ is set using Bundesbank data from which we calculate the share of liquid assets in median gross wealth by income group, such that $\theta^h_t$ is the corresponding share for the income percentile in which $h$ finds itself in period $t$.

The initial value for liquidity is also set using these `liquidity shares', alongside gross wealth data from SOEP.

## Updating panel age

The model assumes that all solar panels have the same maximum lifespan, and the age of each panel in the model is augmented by 1 in each period. The age of panels already existing at the beginning of the simulation is taken from SOEP data. If a panel owned by a household $h$ reaches the maximum lifespan in $t$, the panel is scrapped and the state variable $PV^h_t$ is set to 0. In addition, the feed-in tariff received by $h$, $FIT^h_t$ is set to 0. The household can then (see below) decide whether they wish to buy a new panel.

## Electricity price expectations

In order to form an expectation about whether purchasing a solar panel is a profitable undertaking, households must have an expectation of the future electricity price over the lifespan of the panel. In line with a large literature on alternatives to the rational expectations hypothesis, it is assumed that each household uses *recursive least squares learning* in order to estimate an econometric model of the electricity price using past observations, which is then projected forward to generate a time-series of expected future electricity prices.

In particular, we assume that agents know that changes in the electricity price follow an AR(1) model, but they do not know the parameters of this model. They attempt to learn them using the recursive least squares formula with constant gain:

$$
R^h_t =R^h_{t-1}+\gamma^h\left(x_t x_t'-R^h_{t-1}\right)\\ 
n^h_t =n^h_{t-1}+\gamma^h\left(R^h_t\right)^{-1}x_t(y_t-x_t' n^h_{t-1})
$$

where $x_t$ is the vector of independent variables (in our case, since we are estimating an AR(1) with intercept, this vector will contain the elements 1 and $\Delta p_{t-1}$). $y_t$ is the dependent variable in $t$ (i.e. $\Delta p_{t}$). $R^h_t$ is $h$'s current estimate of the moment matrix of $x$. $n^h_t$ is $h$'s current estimate of the vector of parameters (intercept and AR parameter). $\gamma^h$ is the so-called gain parameter, which determines how sensitive $h$'s estimates are to new observations.

Each household $h$ hence has an internal AR(1) model with the parameters contained in $n^h_t$. Using the current electricity price, they can use this model to project the price forward, generating a time-series of expected future electricity prices which is used below to form an expected revenue from owning a solar panel.

$R^h_t$ and $n^h_t$ are initialised uniformly across households and at the beginning of the simulation, the expectations formation algorithm is trained using the second time-series of electricity prices generated as a training dataset as described above. Note that if $\gamma^h$ differs across households, households will hold heterogeneous expectations.

## Adoption Decision

The decision on whether or not to adopt PV is based on a simple utility maximization framework; every household which does not already own a solar panel makes this decision in every simulation period. By assumption, there exists only one type of solar panel in the model, such that the adoption decision is a binary one between adopting and not adopting. The solar panel has an installation cost $K_t$ which is uniform for every household and which changes over time (if we are simulating past years, empirical data on the cost of solar PV are used; for future years, these data are projected forward).
As mentioned above, every solar panel generates a fixed amount of electricity $G$ per period.

Prior to deciding whether or not to purchase a solar panel based on utility considerations, every household which does not already own PV must check whether they are financially capable of adopting. If the accumulated liquidity of household $h$, $M^h_t$ is greater than $K_t$, $h$ can buy a panel outright and proceeds to the utility maximisation problem. If $M^h_t<K_t$, $h$ must obtain a loan of size $L^h=K_t-M^h_t$.

By assumption, the bank in the model sets a maximum amount which it is prepared to lend to any given household $h$, which is determined by $LTV\cdot K_t$ where $LTV\leq1$ (at present we are in fact working with $LTV=1$ so this constraint is not binding for any agent). If $L^h>LTV\cdot K_t$, the household cannot obtain a loan of sufficient size; they are credit-rationed and cannot adopt. The bank also checks whether the household is financially capable of meeting the payments on a loan of size $L^h$. The interest rate which the bank would charge on a loan to $h$ is given by

$$
    r^h=r_t+\iota \frac{L^h}{LTV\cdot K_t}
$$

i.e. the interest rate charged by the bank increases with the loan to value ratio implied by the loan. $r_t$ is an exogenous base interest rate (if we are simulating past years, the average ECB base rate for that year is used; for future years, we take the currently effective rate and keep it constant in the baseline). Given that loans in the model are assumed to be amortising, and assuming that all loans in the model have a duration equal to the lifetime of a panel, $A$, the per-period payment on a loan of size $L^h$ at rate $r^h$ would be

$$
    S^h=L^h\frac{r^h(1+r^h)^A}{(1+r^h)^A-1}
$$

If $S^h$ exceeds a fraction $DTI$ of the current income of $h$, i.e. if $\frac{S^h}{Y^h_t}>DTI$ the household is also credit-rationed and cannot adopt. Otherwise, they proceed to the utility maximisation problem.

Coming to the utility maximisation part of the adoption decision, we assume that

$$
    U^{h,PV=0}_{t}=0 \quad \forall\  h \in H \ \& \ \forall\  t \in T
$$

i.e. the utility from not adopting PV is always zero for all households. This means that a household will adopt as soon as the utility from doing so is greater than zero (provided that they are not credit-constrained as described above). The utility from adopting is given by

$$
    U_{t}^{h, PV = 1} | (F^{h}=1) = E^h_t(\Pi^h)+\alpha^h \lambda^h_t+\beta Env^{h}\\
    U_{t}^{h, PV = 1} | (F^{h}=0) =0
$$

First of all, note that $U_{t}^{h,PV = 1}$ is conditional on $F^{h}$. $F^{h}$ is a dummy denoting the feasibility of PV, i.e. whether, given the characteristics of the dwelling of household $h$, a solar panel can in fact be installed (e.g. installation may not be technically feasible or there may be administrative rules preventing installation). If $F^{h}=0$, PV cannot be installed and the utility, correspondingly, is zero. At present, $F^h$ is set for each household at the beginning of the simulation and remains fixed thereafter. If a household already owns PV at the beginning, it is set to 1. Otherwise it is set to 1 with probability 1 if the household lives in a house and with probability $p^f<1$ if the household lives in a flat.

Focus now on the case of $F^h=1$. Going from right to left, the term $\beta Env^{h}$ captures the environmental attitude of the household. $Env^h$ is a fixed household characteristic which takes 4 discrete levels (higher value=more concerned about the environment/climate change, the lowest value being 0), calibrated on Gallup survey data from the US. $\beta Env^{h}$ is supposed to reflect the intrinsic utility which $h$ derives from owning PV regardless of whether or not it is profitable to do so.

$\alpha^h \lambda^h_{t}$ captures the element of social influence/emulation, where

$$
    \lambda^h_{t}=\omega^{PV=1}_{d=d^h, t-1}-\omega^{PV=0}_{d=d^h, t-1}
$$

$\omega^{PV=1}_{d=d^h, t-1}$ is the share of households in the same income decile as $h$ who owned PV at the end of the previous period, with $\omega^{PV=0}_{d=d^h, t-1}$ being the corresponding share of households in the same decile who \textit{did not} own PV. $\lambda^h_{t}$ hence takes a value between $-1$ and $1$.

Finally, the term $E^h_{t}(\Pi^h)$ denotes $h$'s expectation at time $t$ of the cumulative profit, $\Pi^h$ which $h$ will be able to derive from owning PV over the lifetime of a panel. This expected profit is given by:

$$
    E^h_{t}(\Pi^h)=\sum_{a = 1}^{A}(\rho^h)^a E^h_{t}(Rev^h_{t+a})-K_t-I^h
$$

$\sum_{a = 1}^{A}E^h_{t}(Rev^h_{t+a})$ is the sum of future revenue/electricity cost saving which the household expects a solar panel to generate over its lifetime of $A$ periods. Recall from above that in any period $t$, the revenue/cost saving which an existing solar panel generates depends on the electricity price, the feed-in tariff received by the owner, as well as the electricity consumption of the household. In the same way, the *expected* revenue/cost saving generated by a panel in some future period $t+a$ depends on:

::: incremental
-   The feed-in tariff which the household would receive if it buys a panel in $t$
-   The electricity price which the household expects to prevail in $t+a$
-   The (expected) electricity consumption of $h$ in $t+a$
:::

The feed-in tariff the agent will receive if it adopts PV in $t$ is known. The expected price in $t+a$ is given by the expectation formation mechanism described above. Regarding electricity consumption, recall that $\overline{E^h_t}$ is assumed to grow at a fixed rate $g^h$ in every period; we assume that the household knows this, meaning that it can easily calculate its electricity consumption in $t+a$. With these elements in place, the expected future revenue/cost saving for the next $A$ periods can be calculated in the same way as *current* revenue/cost saving, described above (i.e. also checking whether the feed-in tariff is larger or smaller than the expected electricity price etc.). Expected revenue/cost saving in future periods is discounted by the individual discount rate of $h$, $\rho^h$. The distribution of discount rates across agents is calibrated based on the existing literature on discount rate elicitation.

$K_t$ is the installation cost of the panel, which is the same for every household.

$I^h$, finally, is the financing cost of the panel. If no loan is needed, the loan cost is obviously 0. If a loan is needed, the cost is equal to the discounted sum of interest payments which will have to be made over the entire term of the loan. As set out above, the interest rate on the loan is given by

$$
    r^h=r_t+\iota \frac{L^h}{LTV\cdot K_t}
$$

from which we can calculate a per-period loan payment as

$$
    S^h=L^h\frac{r^h(1+r^h)^A}{(1+r^h)^A-1}
$$

Knowing the principal and per-period payment, we can calculate an amortisation schedule telling us how much principal and interest the household will have to pay in each future period, which in turn allows us to derive the loan cost as the discounted sum of future interest payments (note that principal payments are not a cost as they do not affect net worth, therefore they should not enter into the calculation of profit!).

Since loans are not costless, it is possible that even if the discounted expected revenue from owning a panel exceeds the installation cost, overall expected profit may turn negative due to the implied financing cost.


In order to somewhat constrain the model dynamics (in particular to avoid the phenomenon of many agents who already owned a solar panel previously not buying a new one once the old one is scrapped, which can occur for some parameter settings), we make one further assumption:

If a household already owned PV in the past but is now no longer an owner because the panel reached its maximum age, then if that panel generated a positive cumulative profit over its lifespan (i.e. $\Pi^h>0$), we set both $Env^{h}$ and $\alpha^h$ to 0 for that household. This means that in considering whether to re-adopt PV, such a household will only consider the expected future profit. All other households sum up all three elements of utility (expected profit, social influence/emulation and environmental attitude).

All households for whom utility is positive, who do not already own a panel and who are not credit-rationed will adopt PV. Any loans taken out to do so are added to their balance sheets, their liquidity is updated, interest rates and loan payments are set (if applicable) and the PV dummies is set to 1. $FIT^h_t$ is set to the feed-in tariff currently in force for all households adopting in $t$ and remains unchanged over the lifetime of the panel.

Since we are also keeping track of the *actual* cumulative profit $\Pi^h$ (not discounted) which a household derives from owning PV, the cumulative profit of all agents adopting PV in $t$ is initialised to $\Pi^h=-K_t$.


## Policy
At present, the model allows for 4 types of policy experiments:

::: incremental
-   A subsidy on the purchase price of a panel, reducing $K_t$ by some percentage
-   An addition to the feed-in tariff on top of the historical values fed exogenously into the model
-   A relaxation of the maximum loan to value constraint (currently not relevant since we already set $LTV=1$)
-   A relaxation of the maximum debt-service to income constraint
:::

In addition, different scenarios/experiments can be simulated by altering the time-series which are fed into the model exogenously (e.g. electricity price time-series, base interest rate, price of PV etc.). Finally, it is easily feasible to switch from the current expectation formation mechanism for the electricity price to a perfect foresight setting as the electricity price is completely independent from endogenous model dynamics. 
