project:
  type: website
  output-dir: docs
  render:
    - 01_about.qmd
    - 02_data.qmd
#    - 03_theory.qmd
    - 04_model.qmd
    - 05_code.qmd
    - 06_modelresults.qmd

website:
  title: "The Agent-Based Model of Technology Adoption (ABM-REN)"
  navbar:
    search: true
    pinned: true
    collapse: true
    right:
      - text: Home
        href: 01_about.qmd 
      - icon: github
        href: https://github.com/gsaabogado
      - icon: twitter
        href: https://twitter.com/gsaabogado
      - text: Personal Site
        href: https://luissarmiento.net/
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Sections"
        contents:
        - 01_about.qmd
        - 02_data.qmd
#        - 03_theory.qmd
        - 04_model.qmd
        - 05_code.qmd
        - 06_modelresults.qmd

format:
  html:
    theme: "flatly"




